[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[[services]]
name = "ehi-backend"
httpPort = 3001
healthcheckPath = "/health"

[deploy.environmentVariables]
NODE_ENV = "production"